### ISSUE TITLE
Are instructions wrong?

### ISSUE THREAD

**Issue by mangan77** [Dijker/nl.regoor.flowbackup#3]
Trying to right click my homey but nothing happens. Firmware is 1.5.8.

**Comment by Dijker** [comment]
Hi Magnus, 
I guess the instructions ar ok, 
but you didn't understand.....  The process will eventually change in the future as we cant use the bearer Token anymore. 
For now: log on to you Homey (preferably from Chrome browser) 
Right klick on Homey and select Copy Link addres with your could ID or internal IP address.
it will contain a bearer token 

http://192.1.2.3/?bearer_token=3******************3
https://5-Your-Homeys-cloud-ID-5.homey.athom.com/?bearer_token=3******************3

just past that in the field, only the bearer will be saved.

**Comment by mangan77** [comment]
Thanks!

I was a bit confused about the browser part and tried to do the same thing in the desktop app. 

Works now. I'll close this issue.
