### ISSUE TITLE
Does not work on Homey 2.0

### ISSUE THREAD

**Issue by pkroeze** [Dijker/nl.regoor.flowbackup#5]

**Comment by Dijker** [comment]
Hi PKRoeze, 
Flow backups is deprecated as Homey from version 2 and up has a much stricter security model. 
It is not possible to create it this way in a Homey App. 

Please look at my new Project at https://community.athom.com/t/community-backup-restore-for-homey-v2-alpha-version/13727 
- Community Backup & Restore for Homey v2 and Up! [Alpha Version]

That is also working for Homey Version 3!
